---
kind: pipeline
name: PR-verify
type: docker

platform:
  os: linux
  arch: amd64

node:
  type: build

trigger:
  branch:
    - master
  event:
    - push
    - pull_request

steps:
      - name: verify_and_test
          image: mozilla/sbt:8u232_1.4.9
          environment:
          commands:
            - sbt scalafmtCheckAll compile
